name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore Pyszne-API-server/Pyszne-API.sln
    - name: Build lib
      run: dotnet build Pyszne-API-server/Pyszne-API.sln --no-restore
    - name: Test lib
      run: dotnet test Pyszne-API-server/Pyszne-API.sln --no-build --verbosity normal
